#!/data/data/com.termux/files/usr/bin/env bash

n="$(printf '\033[0m')"
R="$(printf '\033[1;31m')"
G="$(printf '\033[1;32m')"
Y="$(printf '\033[1;33m')"
W="$(printf '\033[1;37m')"
C="$(printf '\033[1;36m')"

INSTALL() {
  pkgs=($@)

  for pkg in "${pkgs[@]}"; do
          type -p "$pkg" &>/dev/null || {
                  echo -e "\n${R} [${G} ● ${R}]${G} Installing package : ${Y} $pkg ${C}\n"
                  pkg install "$pkg" -y --no-install-recommends
                  echo -e "\n\t${R}● ${Y}${pkg}${G} INSTALLATION COMPLETED ${R}●\n"${n}
          }
  done
  echo -e "\n\t${R}● ${C}[ ${Y}${pkgs[@]} ${C}] ${G}Done ! 🤘 ${R}●\n"${n}
}
clear
INSTALL dialog
# This script will configure a graphical user interface
# (xfce4) in termux
# Creator : @ShivaShirsath
cd $HOME

dialog --colors --infobox "Installing Necessary Packages\n\nPlease wait…" 0 0
sleep 1

clear

dialog --colors --infobox "Installing…\nxfce4 & basic apps" 0 0
sleep 1

apt update -y && apt upgrade -y
INSTALL wget
rm /data/data/com.termux/files/usr/etc/apt/sources.list.d/termux-desktop-xfce.list
wget -P /data/data/com.termux/files/usr/etc/apt/sources.list.d https://raw.githubusercontent.com/Yisus7u7/termux-desktop-xfce/gh-pages/termux-desktop-xfce.list
INSTALL x11-repo
apt update -y
INSTALL xfce4 xfce4-goodies termux-desktop-xfce openjdk-17 florence otter-browser fish 

# ln -s $HOME/storage/shared/AppProjects AppProjects

INSTALL git

dialog --colors --infobox "\Z1Removing…\nTheme & Icons.\Z0" 0 0
sleep 1

rm -rf /data/data/com.termux/files/usr/share/icons
rm -rf /data/data/com.termux/files/usr/share/themes
rm -rf /data/data/com.termux/files/usr/share/backgrounds

mkdir /data/data/com.termux/files/usr/share/backgrounds

dialog --colors --infobox "Installing…\nTheme & Icons." 0 0
sleep 1

PWDx=$PWD
cd /data/data/com.termux/files/usr/share/
wget https://github.com/ShivaShirsath/termux-desktop/raw/main/icons.tar.xz
wget https://github.com/ShivaShirsath/termux-desktop/raw/main/themes.tar.xz
tar -xvf icons.tar.xz
tar -xvf themes.tar.xz
cd /data/data/com.termux/files/usr/share/backgrounds
wget https://github.com/ShivaShirsath/termux-desktop/raw/main/bg_android.jpg
cd $PWDx

dialog --colors --infobox "Setting… Config" 0 0
sleep 1

rm -rf $HOME/.backup
mkdir $HOME/.backup
mv $HOME/.config $HOME/.backup
mv $HOME/.vnc $HOME/.backup
cd $HOME
wget https://github.com/ShivaShirsath/termux-desktop/raw/main/.vnc.tar.xz
tar -xvf .vnc.tar.xz
rm -rf .config
wget https://github.com/ShivaShirsath/termux-desktop/raw/main/.config.tar.xz
tar -xvf .config.tar.xz

dialog --colors --infobox "Installing… VNC" 0 0
sleep 1

PWDx=$PWD
cd $HOME
rm -rf VNC
mkdir VNC
cd VNC

wget https://raw.githubusercontent.com/ShivaShirsath/termux-desktop/main/VNC/install
wget https://raw.githubusercontent.com/ShivaShirsath/termux-desktop/main/VNC/launchVNC
wget https://raw.githubusercontent.com/ShivaShirsath/termux-desktop/main/VNC/progress
wget https://raw.githubusercontent.com/ShivaShirsath/termux-desktop/main/VNC/uninstall
wget https://raw.githubusercontent.com/ShivaShirsath/termux-desktop/main/VNC/vnc

chmod +x *

bash install

cd $PWDx

dialog --colors --infobox "Installing… Folders" 0 0
sleep 1

mkdir $HOME/Desktop 
mkdir $HOME/Downloads 
mkdir $HOME/Templates 
mkdir $HOME/Public 
mkdir $HOME/Documents 
mkdir $HOME/Pictures 
mkdir $HOME/Videos 
termux-setup-storage

exit
